name: Daily Auto Commit

on:
  workflow_dispatch:    # Возможность запустить вручную
  schedule:
    - cron: '0 0 * * *' # Автоматический запуск каждый день в 00:00 UTC

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.name "hoang093"
          git config --global user.email "youremail@example.com"

      - name: Add a new activity log
        run: |
          echo "Auto commit at $(date)" >> activity-log.txt
          git add activity-log.txt
          git commit -m "Automated commit - $(date)"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
